import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { cp, mkdir, mkdtemp, readFile, readdir, rm, stat, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import test from 'node:test';
import { buildPlugin, packagePlugin } from '../scripts/plugin.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const RULES = 'com.github.copilot/rules';

async function fixture(t) {
  const root = await mkdtemp(path.join(tmpdir(), 'hub plugin test '));
  t.after(() => rm(root, { recursive: true, force: true }));
  for (const entry of ['catalog', 'review-pack', 'plugin', 'plugin.json', 'docs/PLUGIN.md', 'CHANGELOG.md']) {
    await mkdir(path.dirname(path.join(root, entry)), { recursive: true });
    await cp(path.join(ROOT, entry), path.join(root, entry), { recursive: true });
  }
  return root;
}

async function assertLinks(root, output) {
  for (const [relative, text] of output) {
    if (!relative.endsWith('.md')) continue;
    for (const match of text.matchAll(/\]\(([^)]+)\)/g)) {
      if (/^(?:[a-z]+:|#)/i.test(match[1])) continue;
      const resolved = path.resolve(root, path.dirname(relative), match[1]);
      assert.ok(resolved.startsWith(root + path.sep), `Link escapes bundle: ${relative}`);
      assert.ok(await stat(resolved), `Broken link: ${relative} -> ${match[1]}`);
    }
  }
}

test('plugin contains every catalog module with original applicability and working review links', async t => {
  const root = await fixture(t);
  const { output } = await buildPlugin(root);
  const catalog = JSON.parse(await readFile(path.join(root, 'catalog/catalog.json')));
  assert.equal([...output.keys()].filter(file => file.startsWith(RULES + '/')).length, catalog.modules.length);
  for (const module of catalog.modules) {
    const source = await readFile(path.join(root, 'catalog', module.path), 'utf8');
    const rule = output.get(`${RULES}/${module.id}.instructions.md`);
    if (module.kind === 'path') {
      assert.equal(rule.match(/^applyTo:.*$/m)[0], source.match(/^applyTo:.*$/m)[0]);
      assert.ok(rule.endsWith(source.split('\n---\n')[1]));
    } else {
      assert.match(rule, /applyTo: "\*\*"/);
      assert.match(rule, /alwaysApply: true/);
      assert.ok(rule.endsWith(source));
    }
  }
  const agent = output.get('com.github.copilot/agents/secure-code-review.agent.md');
  const original = await readFile(path.join(root, 'review-pack/.github/agents/secure-code-review.agent.md'), 'utf8');
  assert.equal(agent.split('\n---\n')[0], original.split('\n---\n')[0]);
  const skill = output.get('skills/secure-code-review-method/SKILL.md');
  const sourceSkill = await readFile(path.join(root, 'review-pack/.github/skills/secure-code-review-method/SKILL.md'), 'utf8');
  assert.equal(skill.split('\n---\n')[0], sourceSkill.split('\n---\n')[0]);
  assert.match(skill, /^name: secure-code-review-method$/m);
  assert.match(skill, /^user-invocable: false$/m);
  assert.match(skill, /^disable-model-invocation: true$/m);
  assert.equal([...output.keys()].filter(file => file.startsWith('com.github.copilot/commands/')).length, 3);
  for (const [file, content] of output) {
    if (file.startsWith('com.github.copilot/commands/')) assert.match(content, /^agent: Secure Code Review$/m);
  }
  const marketplace = JSON.parse(output.get('.github/plugin/marketplace.json'));
  const manifest = JSON.parse(await readFile(path.join(root, 'plugin.json')));
  assert.equal(marketplace.plugins[0].version, manifest.version);
  assert.equal(marketplace.plugins[0].source, './plugins/ai-security-hub');
  await assertLinks(root, output);
  await buildPlugin(root, true);
});

test('check detects changed, missing, and stale files without repairing them', async t => {
  const root = await fixture(t);
  await buildPlugin(root);
  const core = path.join(root, RULES, 'core.instructions.md');
  await writeFile(core, '<!-- Generated by AI Security Hub -->\nchanged\n');
  await assert.rejects(buildPlugin(root, true), /drifted/);
  assert.match(await readFile(core, 'utf8'), /changed/);
  await buildPlugin(root);
  await rm(core);
  await assert.rejects(buildPlugin(root, true), /drifted/);
  await buildPlugin(root);
  const stale = path.join(root, RULES, 'retired.instructions.md');
  await writeFile(stale, '<!-- Generated by AI Security Hub -->\nretired\n');
  await assert.rejects(buildPlugin(root, true), /retired/);
  await buildPlugin(root);
  await assert.rejects(readFile(stale), { code: 'ENOENT' });
});

test('build preserves unrelated files and refuses linked output directories', async t => {
  const root = await fixture(t);
  await buildPlugin(root);
  const personal = path.join(root, RULES, 'personal.instructions.md');
  await writeFile(personal, 'Personal instructions\n');
  await assert.rejects(buildPlugin(root), /unmanaged/);
  assert.equal(await readFile(personal, 'utf8'), 'Personal instructions\n');
  await rm(personal);
  await rm(path.join(root, 'skills'), { recursive: true });
  const outside = path.join(root, 'outside');
  await mkdir(outside);
  await symlink(outside, path.join(root, 'skills'), process.platform === 'win32' ? 'junction' : 'dir');
  await assert.rejects(buildPlugin(root), /Symlinks/);
  assert.deepEqual(await readdir(outside), []);
});

test('session hook returns Local context without using input or modifying the workspace', async t => {
  const root = await fixture(t);
  const { output } = await buildPlugin(root);
  const hooks = JSON.parse(output.get('com.github.copilot/hooks/hooks.json'));
  assert.deepEqual(Object.keys(hooks.hooks), ['SessionStart']);
  const [hook] = hooks.hooks.SessionStart;
  const workspace = path.join(root, 'empty workspace');
  await mkdir(workspace);
  const windows = process.platform === 'win32';
  const result = spawnSync(windows ? 'powershell.exe' : 'sh', windows
    ? ['-NoProfile', '-NonInteractive', '-Command', hook.windows.replaceAll('${PLUGIN_ROOT}', root)]
    : ['-c', hook.command.replaceAll('${PLUGIN_ROOT}', root)], {
    cwd: workspace, encoding: 'utf8', timeout: 5000,
    input: JSON.stringify({ source: 'new', prompt: '$(touch unwanted) `touch unwanted`', cwd: workspace }),
  });
  assert.ifError(result.error);
  assert.equal(result.status, 0, result.stderr);
  const context = JSON.parse(result.stdout).hookSpecificOutput;
  assert.equal(context.hookEventName, 'SessionStart');
  assert.match(context.additionalContext, /applyTo/);
  assert.match(context.additionalContext, /explicitly requested/);
  assert.deepEqual(await readdir(workspace), []);
});

test('archive is self-contained, relocatable, excludes development files, and has a valid checksum', async t => {
  const root = await fixture(t);
  const { output, manifest } = await buildPlugin(root);
  const artifact = await packagePlugin(root);
  const bytes = await readFile(artifact);
  assert.equal(await readFile(`${artifact}.sha256`, 'utf8'),
    `${createHash('sha256').update(bytes).digest('hex')}  ${path.basename(artifact)}\n`);
  const extracted = path.join(root, 'relocated install');
  await mkdir(extracted);
  const result = spawnSync('tar', ['-xzf', artifact, '-C', extracted], { encoding: 'utf8' });
  assert.ifError(result.error);
  assert.equal(result.status, 0, result.stderr);
  const installed = path.join(extracted, `${manifest.name}-native-${manifest.version}`);
  assert.deepEqual((await readdir(installed)).sort(), ['CHANGELOG.md', 'README.md', 'com.github.copilot', 'plugin.json', 'skills']);
  const native = new Map([...output].filter(([file]) => file.startsWith('skills/') || file.startsWith('com.github.copilot/')));
  await assertLinks(installed, native);
  for (const [file, content] of native) {
    assert.equal(await readFile(path.join(installed, file), 'utf8'), content);
  }
});

test('unmapped review links and stale bundles cannot be released', async t => {
  const root = await fixture(t);
  await buildPlugin(root);
  await rm(path.join(root, RULES, 'core.instructions.md'));
  await assert.rejects(packagePlugin(root), /drifted/);
  const source = path.join(root, 'review-pack/.github/agents/secure-code-review.agent.md');
  await writeFile(source, (await readFile(source, 'utf8')) + '\n[missing](../missing.md)\n');
  await assert.rejects(buildPlugin(root), /Unmapped review-pack link/);
});
