[CmdletBinding()]
param(
    [string]$Target = ".",
    [string]$Preset = "full",
    [ValidateSet("path-specific", "universal")]
    [string]$Mode = "path-specific",
    [string[]]$Include = @(),
    [string[]]$Exclude = @(),
    [switch]$NoDetect,
    [switch]$Force,
    [switch]$DryRun,
    [switch]$Check,
    [switch]$List
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

$RepoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$CatalogRoot = Join-Path $RepoRoot "catalog"
$CatalogFile = Join-Path $CatalogRoot "catalog.json"
$ReviewRoot = Join-Path $RepoRoot "review-pack"
$StateRelative = ".github/.ai-security-hub.json"
$LocalRelative = ".github/ai-security-hub-local.md"
$MarkerPrefix = "<!-- Generated by AI Security Hub"
$MaxDetectionFileBytes = 1000000
$Utf8NoBom = New-Object Text.UTF8Encoding($false)
$IgnoredParts = @(".git", ".hg", ".svn", ".venv", "__pycache__", "node_modules", "vendor", "dist", "build", "target", "coverage")

function Fail([string]$Message) {
    throw $Message
}

function Normalize-Lf([string]$Text) {
    return $Text.Replace("`r`n", "`n").Replace("`r", "`n")
}

function Read-Text([string]$Path) {
    return Normalize-Lf ([IO.File]::ReadAllText($Path))
}

function Get-ObjectProperty($Object, [string]$Name) {
    if ($null -eq $Object) { return $null }
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    return $property.Value
}

function Get-RelativePath([string]$BasePath, [string]$FullPath) {
    $prefix = $BasePath.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
    $relative = $FullPath.Substring($prefix.Length).TrimStart([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
    return $relative.Replace("\", "/")
}

function Test-CopilotCustomization([string]$RelativePath) {
    $normalized = "/" + $RelativePath.Replace("\", "/")
    return $normalized -match '/\.github/(agents|prompts|skills|instructions)/' -or
        $normalized.EndsWith("/.github/copilot-instructions.md", [StringComparison]::Ordinal) -or
        $normalized.EndsWith("/.github/.ai-security-hub.json", [StringComparison]::Ordinal)
}

function Split-Ids([string[]]$Values) {
    $result = New-Object 'System.Collections.Generic.List[string]'
    foreach ($value in @($Values)) {
        foreach ($part in @($value -split ',')) {
            $trimmed = $part.Trim()
            if ($trimmed) { $result.Add($trimmed) }
        }
    }
    return @($result)
}

function Convert-GlobToRegex([string]$Pattern) {
    $builder = New-Object Text.StringBuilder
    [void]$builder.Append('^')
    $index = 0
    while ($index -lt $Pattern.Length) {
        $character = $Pattern[$index]
        if ($character -eq '*') {
            if (($index + 1) -lt $Pattern.Length -and $Pattern[$index + 1] -eq '*') {
                if (($index + 2) -lt $Pattern.Length -and $Pattern[$index + 2] -eq '/') {
                    [void]$builder.Append('(?:.*/)?')
                    $index += 3
                    continue
                }
                [void]$builder.Append('.*')
                $index += 2
                continue
            }
            [void]$builder.Append('[^/]*')
            $index += 1
            continue
        }
        if ($character -eq '?') {
            [void]$builder.Append('[^/]')
        } else {
            [void]$builder.Append([Regex]::Escape([string]$character))
        }
        $index += 1
    }
    [void]$builder.Append('$')
    return $builder.ToString()
}

function Test-PathMatches([string]$RelativePath, [string]$Pattern) {
    $normalized = $RelativePath.Replace("\", "/")
    while ($normalized.StartsWith("./", [StringComparison]::Ordinal)) { $normalized = $normalized.Substring(2) }
    return [Regex]::IsMatch($normalized, (Convert-GlobToRegex $Pattern), [Text.RegularExpressions.RegexOptions]::CultureInvariant)
}

function Parse-Module([string]$Text, [string]$Source) {
    $normalized = Normalize-Lf $Text
    if (-not $normalized.StartsWith("---`n")) { Fail "Path-specific module lacks frontmatter: $Source" }
    $closing = $normalized.IndexOf("`n---`n", 4, [StringComparison]::Ordinal)
    if ($closing -lt 0) { Fail "Path-specific module has unterminated frontmatter: $Source" }
    $frontmatter = $normalized.Substring(0, $closing + 5).TrimEnd("`n")
    $body = $normalized.Substring($closing + 5).Trim("`n")
    return @{ Frontmatter = $frontmatter; Body = $body }
}

function Get-ApplyPatterns($Module) {
    $source = Join-Path $CatalogRoot $Module.path
    $parsed = Parse-Module (Read-Text $source) $source
    foreach ($line in @($parsed.Frontmatter -split "`n")) {
        if ($line.StartsWith("applyTo:")) {
            $value = $line.Substring($line.IndexOf(':') + 1).Trim()
            if ($value.Length -ge 2 -and (($value[0] -eq '"' -and $value[$value.Length - 1] -eq '"') -or ($value[0] -eq "'" -and $value[$value.Length - 1] -eq "'"))) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            return @($value -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })
        }
    }
    Fail "Path-specific module lacks applyTo: $source"
}

function Test-ModuleApplies($Module, [object[]]$Files) {
    foreach ($pattern in @(Get-ApplyPatterns $Module)) {
        foreach ($file in @($Files)) {
            if (Test-PathMatches $file.Relative $pattern) { return $true }
        }
    }
    return $false
}

function Format-JsonArray([string[]]$Values, [int]$BaseIndent = 2) {
    if (@($Values).Count -eq 0) { return "[]" }
    $itemIndent = " " * ($BaseIndent + 2)
    $closingIndent = " " * $BaseIndent
    $lines = foreach ($value in @($Values)) {
        $encoded = ConvertTo-Json -InputObject ([string]$value) -Compress
        "$itemIndent$encoded"
    }
    return "[`n" + ($lines -join ",`n") + "`n$closingIndent]"
}

function New-StateContent([string]$Version, [string]$SelectedPreset, [string]$SelectedMode, [string[]]$Modules, [string[]]$ManagedFiles) {
    $managed = Format-JsonArray $ManagedFiles 2
    $selected = Format-JsonArray $Modules 2
    return ((@(
        "{",
        "  `"catalogVersion`": `"$Version`",",
        "  `"generator`": `"AI Security Hub`",",
        "  `"managedFiles`": $managed,",
        "  `"mode`": `"$SelectedMode`",",
        "  `"modules`": $selected,",
        "  `"preset`": `"$SelectedPreset`",",
        "  `"reviewPack`": true,",
        "  `"schemaVersion`": 1",
        "}"
    ) -join "`n") + "`n")
}

function Test-Generated([string]$Path) {
    try {
        $content = [IO.File]::ReadAllText($Path)
        return $content.Contains($MarkerPrefix) -or $content.Contains('"generator": "AI Security Hub"')
    } catch {
        return $false
    }
}

function Assert-SafeOutputPath([string]$TargetRoot, [string]$Relative) {
    $parts = @($Relative.Replace("\", "/") -split '/')
    if (-not $Relative.StartsWith(".github/", [StringComparison]::Ordinal) -or $parts -contains "..") {
        Fail "Unsafe managed path: $Relative"
    }
    $current = $TargetRoot
    foreach ($part in $parts) {
        $current = Join-Path $current $part
        if (Test-Path -LiteralPath $current) {
            $item = Get-Item -LiteralPath $current -Force
            if (($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) {
                Fail "Refusing to follow symlink or reparse point in generated path: $current"
            }
        }
    }
}

try {
    if ($Check -and $DryRun) { Fail "-Check and -DryRun are mutually exclusive" }
    if (-not (Test-Path -LiteralPath $CatalogFile -PathType Leaf)) { Fail "Cannot find $CatalogFile" }
    $catalog = ConvertFrom-Json (Read-Text $CatalogFile)

    $moduleMap = @{}
    foreach ($module in @($catalog.modules)) { $moduleMap[[string]$module.id] = $module }

    if ($List) {
        $currentGroup = $null
        foreach ($module in @($catalog.modules)) {
            if ($module.group -ne $currentGroup) {
                $currentGroup = $module.group
                Write-Output ""
                Write-Output ("{0}:" -f $currentGroup)
            }
            $detectedLabel = if ($null -ne (Get-ObjectProperty $module "detect")) { " [auto-detected]" } else { "" }
            Write-Output ("  {0,-30} {1}{2}" -f $module.id, $module.description, $detectedLabel)
        }
        exit 0
    }

    if (-not (Test-Path -LiteralPath $Target -PathType Container)) { Fail "Target is not a directory: $Target" }
    $resolvedTarget = Resolve-Path -LiteralPath $Target
    $TargetRoot = $resolvedTarget.ProviderPath.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
    if (-not $TargetRoot) { $TargetRoot = [IO.Path]::GetPathRoot((Resolve-Path -LiteralPath $Target).Path) }
    if ($TargetRoot -eq [IO.Path]::GetPathRoot($TargetRoot)) { Fail "Refusing to use a filesystem root as a target" }

    $resolved = New-Object 'System.Collections.Generic.List[string]'
    $resolvedSeen = @{}
    $resolving = @{}
    function Resolve-Preset([string]$Name) {
        $property = $catalog.presets.PSObject.Properties[$Name]
        if ($null -eq $property) { Fail "Unknown preset '$Name'" }
        if ($resolving.ContainsKey($Name)) { Fail "Preset cycle detected at '$Name'" }
        $resolving[$Name] = $true
        foreach ($itemValue in @($property.Value)) {
            $item = [string]$itemValue
            if ($item -eq "*") {
                foreach ($allModule in @($catalog.modules)) {
                    $id = [string]$allModule.id
                    if (-not $resolvedSeen.ContainsKey($id)) { $resolved.Add($id); $resolvedSeen[$id] = $true }
                }
            } elseif ($item.StartsWith("@")) {
                Resolve-Preset $item.Substring(1)
            } else {
                if (-not $moduleMap.ContainsKey($item)) { Fail "Preset '$Name' references unknown module '$item'" }
                if (-not $resolvedSeen.ContainsKey($item)) { $resolved.Add($item); $resolvedSeen[$item] = $true }
            }
        }
        $resolving.Remove($Name)
    }
    Resolve-Preset $Preset

    $includeIds = @(Split-Ids $Include)
    $excludeIds = @(Split-Ids $Exclude)
    foreach ($id in @($includeIds + $excludeIds)) {
        if (-not $moduleMap.ContainsKey($id)) { Fail "Unknown module: $id" }
    }

    $files = New-Object 'System.Collections.Generic.List[object]'
    foreach ($file in @(Get-ChildItem -LiteralPath $TargetRoot -Recurse -Force -File)) {
        if (($file.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0) { continue }
        $relative = Get-RelativePath $TargetRoot $file.FullName
        $ignored = $false
        foreach ($part in @($relative -split '/')) {
            if ($IgnoredParts -contains $part) { $ignored = $true; break }
        }
        if (-not $ignored -and -not (Test-CopilotCustomization $relative)) {
            $files.Add([PSCustomObject]@{ Relative = $relative; FullName = $file.FullName; Length = $file.Length })
        }
    }

    $detectedIds = New-Object 'System.Collections.Generic.List[string]'
    if (-not $NoDetect) {
        foreach ($module in @($catalog.modules)) {
            $detect = Get-ObjectProperty $module "detect"
            if ($null -eq $detect) { continue }
            $matched = $false
            foreach ($pattern in @(Get-ObjectProperty $detect "files")) {
                foreach ($file in $files.ToArray()) {
                    if (Test-PathMatches $file.Relative ([string]$pattern)) { $matched = $true; break }
                }
                if ($matched) { break }
            }
            if (-not $matched) {
                foreach ($contentRule in @(Get-ObjectProperty $detect "content")) {
                    if ($null -eq $contentRule) { continue }
                    foreach ($file in $files.ToArray()) {
                        $fileMatched = $false
                        foreach ($pattern in @(Get-ObjectProperty $contentRule "files")) {
                            if (Test-PathMatches $file.Relative ([string]$pattern)) { $fileMatched = $true; break }
                        }
                        if (-not $fileMatched -or $file.Length -gt $MaxDetectionFileBytes) { continue }
                        try { $text = [IO.File]::ReadAllText($file.FullName) } catch { $text = "" }
                        foreach ($needle in @(Get-ObjectProperty $contentRule "needles")) {
                            if ($text.IndexOf([string]$needle, [StringComparison]::OrdinalIgnoreCase) -ge 0) { $matched = $true; break }
                        }
                        if ($matched) { break }
                    }
                    if ($matched) { break }
                }
            }
            if ($matched) { $detectedIds.Add([string]$module.id) }
        }
    }

    $wanted = @{}
    foreach ($id in $resolved.ToArray() + $detectedIds.ToArray() + @($includeIds)) { if ($id) { $wanted[$id] = $true } }
    $excluded = @{}
    foreach ($id in @($excludeIds)) { if ($id) { $excluded[$id] = $true } }
    $alwaysInclude = @{}
    foreach ($id in $detectedIds.ToArray() + @($includeIds)) { if ($id) { $alwaysInclude[$id] = $true } }
    $selectedIds = New-Object 'System.Collections.Generic.List[string]'
    foreach ($module in @($catalog.modules)) {
        $id = [string]$module.id
        if ($wanted.ContainsKey($id) -and -not $excluded.ContainsKey($id)) { $selectedIds.Add($id) }
    }
    if (-not ($selectedIds.ToArray() -contains "core")) { Fail "The core module is required; do not exclude it" }

    $repositoryIds = @($selectedIds | Where-Object { $moduleMap[$_].kind -eq "repository" })
    $pathIds = @($selectedIds | Where-Object { $moduleMap[$_].kind -eq "path" })
    $applicablePathIds = New-Object 'System.Collections.Generic.List[string]'
    if ($Mode -eq "universal") {
        foreach ($id in $pathIds) {
            if ($alwaysInclude.ContainsKey($id) -or (Test-ModuleApplies $moduleMap[$id] $files.ToArray())) { $applicablePathIds.Add($id) }
        }
    } else {
        foreach ($id in $pathIds) { $applicablePathIds.Add($id) }
    }

    $outputs = @{}
    $emittedIds = @($repositoryIds) + $applicablePathIds.ToArray()
    $sections = New-Object 'System.Collections.Generic.List[string]'
    $sections.Add("$MarkerPrefix $($catalog.catalogVersion). Modules: $($emittedIds -join ', '). Do not edit; regenerate. -->")
    foreach ($id in $repositoryIds) {
        $sections.Add((Read-Text (Join-Path $CatalogRoot $moduleMap[$id].path)).TrimEnd("`n"))
    }
    if ($Mode -eq "universal") {
        foreach ($id in $applicablePathIds.ToArray()) {
            $source = Join-Path $CatalogRoot $moduleMap[$id].path
            $parsed = Parse-Module (Read-Text $source) $source
            $sections.Add("<!-- AI Security Hub module: $id -->`n$($parsed.Body)")
        }
    }
    $localPath = Join-Path $TargetRoot $LocalRelative
    if ((Test-Path -LiteralPath $localPath -PathType Leaf) -and (Get-Item -LiteralPath $localPath).Length -gt 0) {
        $localText = (Read-Text $localPath).Trim("`n")
        $sections.Add("# Repository-specific instructions`n`nThese project instructions supplement but do not silently weaken the secure-development baseline.`n`n$localText")
    }
    $outputs[".github/copilot-instructions.md"] = ($sections -join "`n`n").TrimEnd("`n") + "`n"

    if ($Mode -eq "path-specific") {
        foreach ($id in $pathIds) {
            $source = Join-Path $CatalogRoot $moduleMap[$id].path
            $parsed = Parse-Module (Read-Text $source) $source
            $outputs[".github/instructions/$id.instructions.md"] = "$($parsed.Frontmatter)`n`n$MarkerPrefix $($catalog.catalogVersion). Modules: $id. Do not edit; regenerate. -->`n`n$($parsed.Body)`n"
        }
    }

    foreach ($reviewFile in @(Get-ChildItem -LiteralPath $ReviewRoot -Recurse -Force -File)) {
        $relative = Get-RelativePath $ReviewRoot $reviewFile.FullName
        $outputs[$relative] = (Read-Text $reviewFile.FullName)
    }

    [string[]]$managedFiles = @($outputs.Keys)
    [Array]::Sort($managedFiles, [StringComparer]::Ordinal)
    $outputs[$StateRelative] = New-StateContent ([string]$catalog.catalogVersion) $Preset $Mode $selectedIds.ToArray() $managedFiles

    $writes = New-Object 'System.Collections.Generic.List[string]'
    $stale = New-Object 'System.Collections.Generic.List[string]'
    $unchanged = New-Object 'System.Collections.Generic.List[string]'
    foreach ($relative in @($outputs.Keys | Sort-Object)) {
        Assert-SafeOutputPath $TargetRoot $relative
        $destination = Join-Path $TargetRoot $relative
        if (Test-Path -LiteralPath $destination -PathType Leaf) {
            $existing = [IO.File]::ReadAllText($destination)
            if ($existing -ceq $outputs[$relative]) { $unchanged.Add($relative); continue }
            if (-not $Force -and -not (Test-Generated $destination)) {
                Fail "Refusing to overwrite file not generated by AI Security Hub: $destination. Merge it manually or rerun with -Force."
            }
        }
        $writes.Add($relative)
    }

    $statePath = Join-Path $TargetRoot $StateRelative
    if (Test-Path -LiteralPath $statePath -PathType Leaf) {
        try { $priorState = ConvertFrom-Json ([IO.File]::ReadAllText($statePath)) } catch { Fail "Cannot parse generated state: $statePath" }
        foreach ($relativeValue in @($priorState.managedFiles)) {
            $relative = [string]$relativeValue
            if ($outputs.ContainsKey($relative)) { continue }
            Assert-SafeOutputPath $TargetRoot $relative
            $destination = Join-Path $TargetRoot $relative
            if (Test-Path -LiteralPath $destination -PathType Leaf) {
                if (-not (Test-Generated $destination)) { Fail "Refusing to remove modified generated file: $destination" }
                $stale.Add($relative)
            }
        }
    }

    Write-Output "Target: $TargetRoot"
    Write-Output "Mode: $Mode; preset: $Preset"
    Write-Output "Modules ($($selectedIds.Count)): $($selectedIds.ToArray() -join ', ')"
    Write-Output "Review pack: enabled"

    if ($Check) {
        if ($writes.Count -gt 0 -or $stale.Count -gt 0) {
            foreach ($relative in $writes) { Write-Output "DRIFT write $relative" }
            foreach ($relative in $stale) { Write-Output "DRIFT remove $relative" }
            exit 1
        }
        Write-Output "Up to date ($($unchanged.Count) files)."
        exit 0
    }

    if ($DryRun) {
        foreach ($relative in $writes) { Write-Output "WOULD WRITE $relative" }
        foreach ($relative in $stale) { Write-Output "WOULD REMOVE $relative" }
        if ($writes.Count -eq 0 -and $stale.Count -eq 0) { Write-Output "No changes." }
        exit 0
    }

    foreach ($relative in $writes) {
        $destination = Join-Path $TargetRoot $relative
        $parent = Split-Path -Parent $destination
        [IO.Directory]::CreateDirectory($parent) | Out-Null
        $temporary = Join-Path $parent (".ai-security-hub." + [Guid]::NewGuid().ToString("N"))
        try {
            [IO.File]::WriteAllText($temporary, [string]$outputs[$relative], $Utf8NoBom)
            Move-Item -LiteralPath $temporary -Destination $destination -Force
        } finally {
            if (Test-Path -LiteralPath $temporary) { Remove-Item -LiteralPath $temporary -Force }
        }
        Write-Output "WROTE $relative"
    }
    foreach ($relative in $stale) {
        Remove-Item -LiteralPath (Join-Path $TargetRoot $relative) -Force
        Write-Output "REMOVED $relative"
    }
    if ($writes.Count -eq 0 -and $stale.Count -eq 0) { Write-Output "No changes." }
    exit 0
} catch {
    [Console]::Error.WriteLine("error: " + $_.Exception.Message + "`n" + $_.InvocationInfo.PositionMessage)
    exit 2
}
