#!/usr/bin/env bash
set -euo pipefail
export LC_ALL=C

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
CATALOG_ROOT="$REPO_ROOT/catalog"
CATALOG_FILE="$CATALOG_ROOT/catalog.json"
REVIEW_ROOT="$REPO_ROOT/review-pack"
STATE_REL=".github/.skills-hub.json"
LOCAL_REL=".github/skills-hub-local.md"
MARKER_PREFIX="<!-- Generated by Skills Hub"
MAX_DETECTION_FILE_BYTES=1000000

TARGET="."
PRESET="full"
MODE="path-specific"
NO_DETECT=false
FORCE=false
DRY_RUN=false
CHECK=false
LIST=false
declare -a INCLUDE_IDS=()
declare -a EXCLUDE_IDS=()
declare -a DISCOVERED_REL=()
declare -a DISCOVERED_ABS=()
declare -a DETECTED_IDS=()
declare -a SELECTED_IDS=()

usage() {
  cat <<'EOF'
Generate GitHub Copilot instructions and the read-only Skills Hub review pack.

Usage: scripts/build.sh [options]
  --target DIR             Repository to receive .github files (default: current directory)
  --preset NAME            Catalog preset (default: full)
  --mode MODE              path-specific or universal (default: path-specific)
  --include IDS            Comma-separated module IDs to add; may be repeated
  --exclude IDS            Comma-separated module IDs to remove; may be repeated
  --no-detect              Disable stack detection
  --force                  Replace existing files not owned by Skills Hub
  --dry-run                Show changes without writing
  --check                  Exit 1 when generated output has drifted
  --list                   List catalog modules
  --help                    Show this help

Requirements: Bash 4+ and jq 1.6+.
EOF
}

fail() {
  printf 'error: %s\n' "$*" >&2
  exit 2
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "Required command not found: $1"
}

append_csv() {
  local value="$1"
  local destination="$2"
  local -a parts=()
  local part
  IFS=',' read -r -a parts <<< "$value"
  for part in "${parts[@]}"; do
    part="${part#"${part%%[![:space:]]*}"}"
    part="${part%"${part##*[![:space:]]}"}"
    [[ -n "$part" ]] || continue
    if [[ "$destination" == "include" ]]; then
      INCLUDE_IDS+=("$part")
    else
      EXCLUDE_IDS+=("$part")
    fi
  done
}

while (($#)); do
  case "$1" in
    --target) (($# >= 2)) || fail "--target requires a value"; TARGET="$2"; shift 2 ;;
    --preset) (($# >= 2)) || fail "--preset requires a value"; PRESET="$2"; shift 2 ;;
    --mode) (($# >= 2)) || fail "--mode requires a value"; MODE="$2"; shift 2 ;;
    --include) (($# >= 2)) || fail "--include requires a value"; append_csv "$2" include; shift 2 ;;
    --exclude) (($# >= 2)) || fail "--exclude requires a value"; append_csv "$2" exclude; shift 2 ;;
    --no-detect) NO_DETECT=true; shift ;;
    --force) FORCE=true; shift ;;
    --dry-run) DRY_RUN=true; shift ;;
    --check) CHECK=true; shift ;;
    --list) LIST=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) fail "Unknown option: $1" ;;
  esac
done

[[ "$MODE" == "path-specific" || "$MODE" == "universal" ]] || fail "--mode must be path-specific or universal"
! $CHECK || ! $DRY_RUN || fail "--check and --dry-run are mutually exclusive"
require_command jq
jq empty "$CATALOG_FILE" >/dev/null 2>&1 || fail "Cannot parse $CATALOG_FILE"

if $LIST; then
  jq -r '.modules[] | [.group, .id, .description, (if .detect then " [auto-detected]" else "" end)] | @tsv' "$CATALOG_FILE" |
    awk -F '\t' 'BEGIN { group="" } $1 != group { group=$1; printf "\n%s:\n", group } { printf "  %-30s %s%s\n", $2, $3, $4 }'
  exit 0
fi

[[ -d "$TARGET" ]] || fail "Target is not a directory: $TARGET"
TARGET="$(cd -- "$TARGET" && pwd -P)"
[[ "$TARGET" != "/" ]] || fail "Refusing to use the filesystem root as a target"

declare -A RESOLVED_SEEN=()
declare -A RESOLVING=()
declare -a PRESET_IDS=()

resolve_preset() {
  local name="$1"
  local item child
  jq -e --arg name "$name" '.presets[$name] != null' "$CATALOG_FILE" >/dev/null ||
    fail "Unknown preset '$name'"
  [[ -z "${RESOLVING[$name]:-}" ]] || fail "Preset cycle detected at '$name'"
  RESOLVING[$name]=1
  while IFS= read -r item; do
    if [[ "$item" == "*" ]]; then
      while IFS= read -r child; do
        if [[ -z "${RESOLVED_SEEN[$child]:-}" ]]; then
          PRESET_IDS+=("$child")
          RESOLVED_SEEN[$child]=1
        fi
      done < <(jq -r '.modules[].id' "$CATALOG_FILE")
    elif [[ "$item" == @* ]]; then
      resolve_preset "${item#@}"
    else
      jq -e --arg id "$item" 'any(.modules[]; .id == $id)' "$CATALOG_FILE" >/dev/null ||
        fail "Preset '$name' references unknown module '$item'"
      if [[ -z "${RESOLVED_SEEN[$item]:-}" ]]; then
        PRESET_IDS+=("$item")
        RESOLVED_SEEN[$item]=1
      fi
    fi
  done < <(jq -r --arg name "$name" '.presets[$name][]' "$CATALOG_FILE")
  unset 'RESOLVING[$name]'
}

resolve_preset "$PRESET"

declare -A KNOWN_IDS=()
while IFS= read -r module_id; do KNOWN_IDS[$module_id]=1; done < <(jq -r '.modules[].id' "$CATALOG_FILE")
for module_id in "${INCLUDE_IDS[@]}" "${EXCLUDE_IDS[@]}"; do
  [[ -z "$module_id" || -n "${KNOWN_IDS[$module_id]:-}" ]] || fail "Unknown module: $module_id"
done

is_ignored_relative() {
  local relative="$1"
  local part
  IFS='/' read -r -a path_parts <<< "$relative"
  for part in "${path_parts[@]}"; do
    case "$part" in
      .git|.hg|.svn|.venv|__pycache__|node_modules|vendor|dist|build|target|coverage) return 0 ;;
    esac
  done
  return 1
}

is_copilot_customization() {
  local relative="/$1"
  case "$relative" in
    */.github/agents/*|*/.github/prompts/*|*/.github/skills/*|*/.github/instructions/*|*/.github/copilot-instructions.md|*/.github/.skills-hub.json) return 0 ;;
  esac
  return 1
}

while IFS= read -r -d '' path; do
  [[ -f "$path" && ! -L "$path" ]] || continue
  relative="${path#"$TARGET"/}"
  is_ignored_relative "$relative" && continue
  is_copilot_customization "$relative" && continue
  DISCOVERED_REL+=("$relative")
  DISCOVERED_ABS+=("$path")
done < <(find "$TARGET" -type f -print0)

path_matches() {
  local relative="${1#./}"
  local pattern="$2"
  [[ "$relative" == $pattern ]] && return 0
  if [[ "$pattern" == '**/'* ]]; then
    pattern="${pattern#\*\*/}"
    [[ "$relative" == $pattern ]] && return 0
  fi
  return 1
}

join_ids() {
  local result='' separator=''
  local value
  for value in "$@"; do
    result+="$separator$value"
    separator=', '
  done
  printf '%s' "$result"
}

file_size() {
  stat -c '%s' "$1" 2>/dev/null || stat -f '%z' "$1" 2>/dev/null || printf '%s' "$((MAX_DETECTION_FILE_BYTES + 1))"
}

detect_modules() {
  local module_count index module_id matched relative absolute size needle content_count rule_index
  local -a patterns=() content_patterns=() needles=()
  module_count="$(jq '.modules | length' "$CATALOG_FILE")"
  for ((index=0; index<module_count; index++)); do
    jq -e ".modules[$index].detect != null" "$CATALOG_FILE" >/dev/null || continue
    module_id="$(jq -r ".modules[$index].id" "$CATALOG_FILE")"
    matched=false
    mapfile -t patterns < <(jq -r ".modules[$index].detect.files[]?" "$CATALOG_FILE")
    for pattern in "${patterns[@]}"; do
      for relative in "${DISCOVERED_REL[@]}"; do
        if path_matches "$relative" "$pattern"; then matched=true; break 2; fi
      done
    done
    if ! $matched; then
      content_count="$(jq ".modules[$index].detect.content // [] | length" "$CATALOG_FILE")"
      for ((rule_index=0; rule_index<content_count; rule_index++)); do
        mapfile -t content_patterns < <(jq -r ".modules[$index].detect.content[$rule_index].files[]" "$CATALOG_FILE")
        mapfile -t needles < <(jq -r ".modules[$index].detect.content[$rule_index].needles[]" "$CATALOG_FILE")
        for file_index in "${!DISCOVERED_REL[@]}"; do
          relative="${DISCOVERED_REL[$file_index]}"
          absolute="${DISCOVERED_ABS[$file_index]}"
          file_matched=false
          for pattern in "${content_patterns[@]}"; do
            if path_matches "$relative" "$pattern"; then file_matched=true; break; fi
          done
          $file_matched || continue
          size="$(file_size "$absolute")"
          ((size <= MAX_DETECTION_FILE_BYTES)) || continue
          for needle in "${needles[@]}"; do
            if grep -Fqi -- "$needle" "$absolute" 2>/dev/null; then matched=true; break 3; fi
          done
        done
      done
    fi
    $matched && DETECTED_IDS+=("$module_id")
  done
  return 0
}

if ! $NO_DETECT; then detect_modules; fi

declare -A WANTED=()
declare -A EXCLUDED=()
declare -A ALWAYS_INCLUDE=()
for module_id in "${PRESET_IDS[@]}" "${DETECTED_IDS[@]}" "${INCLUDE_IDS[@]}"; do
  [[ -n "$module_id" ]] && WANTED[$module_id]=1
done
for module_id in "${EXCLUDE_IDS[@]}"; do [[ -n "$module_id" ]] && EXCLUDED[$module_id]=1; done
for module_id in "${DETECTED_IDS[@]}" "${INCLUDE_IDS[@]}"; do [[ -n "$module_id" ]] && ALWAYS_INCLUDE[$module_id]=1; done
while IFS= read -r module_id; do
  [[ -n "${WANTED[$module_id]:-}" && -z "${EXCLUDED[$module_id]:-}" ]] && SELECTED_IDS+=("$module_id")
done < <(jq -r '.modules[].id' "$CATALOG_FILE")
for module_id in "${SELECTED_IDS[@]}"; do [[ "$module_id" == "core" ]] && has_core=true; done
[[ "${has_core:-false}" == true ]] || fail "The core module is required; do not exclude it"

extract_frontmatter() {
  awk '
    NR == 1 && $0 == "---" { in_fm=1 }
    in_fm { if (count++) printf "\n"; printf "%s", $0 }
    NR > 1 && in_fm && $0 == "---" { exit }
  ' "$1"
}

extract_body() {
  awk '
    NR == 1 && $0 == "---" { in_fm=1; next }
    in_fm && $0 == "---" { in_fm=0; next }
    in_fm { next }
    !started && $0 == "" { next }
    { lines[++count]=$0; started=1 }
    END { while (count > 0 && lines[count] == "") count--; for (i=1; i<=count; i++) { if (i > 1) printf "\n"; printf "%s", lines[i] } }
  ' "$1"
}

emit_trimmed_file() {
  awk '{ lines[NR]=$0 } END { last=NR; while (last > 0 && lines[last] == "") last--; for (i=1; i<=last; i++) { if (i > 1) printf "\n"; printf "%s", lines[i] } }' "$1"
}

module_applies() {
  local source="$1"
  local line value pattern relative
  local -a patterns=()
  line="$(grep -m1 '^applyTo:' "$source" || true)"
  [[ -n "$line" ]] || fail "Path-specific module lacks applyTo: $source"
  value="${line#applyTo: }"
  value="${value#\"}"; value="${value%\"}"
  value="${value#\'}"; value="${value%\'}"
  IFS=',' read -r -a patterns <<< "$value"
  for pattern in "${patterns[@]}"; do
    pattern="${pattern#"${pattern%%[![:space:]]*}"}"
    pattern="${pattern%"${pattern##*[![:space:]]}"}"
    for relative in "${DISCOVERED_REL[@]}"; do path_matches "$relative" "$pattern" && return 0; done
  done
  return 1
}

STAGE="$(mktemp -d)"
cleanup() { rm -rf -- "$STAGE"; }
trap cleanup EXIT
mkdir -p -- "$STAGE/.github"

catalog_version="$(jq -r '.catalogVersion' "$CATALOG_FILE")"
selected_csv="$(join_ids "${SELECTED_IDS[@]}")"

declare -a REPOSITORY_IDS=()
declare -a PATH_IDS=()
for module_id in "${SELECTED_IDS[@]}"; do
  kind="$(jq -r --arg id "$module_id" '.modules[] | select(.id == $id) | .kind' "$CATALOG_FILE")"
  if [[ "$kind" == "repository" ]]; then REPOSITORY_IDS+=("$module_id"); else PATH_IDS+=("$module_id"); fi
done

declare -a APPLICABLE_PATH_IDS=()
if [[ "$MODE" == "universal" ]]; then
  for module_id in "${PATH_IDS[@]}"; do
    source_rel="$(jq -r --arg id "$module_id" '.modules[] | select(.id == $id) | .path' "$CATALOG_FILE")"
    if [[ -n "${ALWAYS_INCLUDE[$module_id]:-}" ]] || module_applies "$CATALOG_ROOT/$source_rel"; then
      APPLICABLE_PATH_IDS+=("$module_id")
    fi
  done
else
  APPLICABLE_PATH_IDS=("${PATH_IDS[@]}")
fi

declare -a EMITTED_IDS=("${REPOSITORY_IDS[@]}" "${APPLICABLE_PATH_IDS[@]}")
emitted_csv="$(join_ids "${EMITTED_IDS[@]}")"
core_output="$STAGE/.github/copilot-instructions.md"
{
  printf '%s %s. Modules: %s. Do not edit; regenerate. -->' "$MARKER_PREFIX" "$catalog_version" "$emitted_csv"
  for module_id in "${REPOSITORY_IDS[@]}"; do
    source_rel="$(jq -r --arg id "$module_id" '.modules[] | select(.id == $id) | .path' "$CATALOG_FILE")"
    printf '\n\n'
    emit_trimmed_file "$CATALOG_ROOT/$source_rel"
  done
  if [[ "$MODE" == "universal" ]]; then
    for module_id in "${APPLICABLE_PATH_IDS[@]}"; do
      source_rel="$(jq -r --arg id "$module_id" '.modules[] | select(.id == $id) | .path' "$CATALOG_FILE")"
      printf '\n\n<!-- Skills Hub module: %s -->\n' "$module_id"
      extract_body "$CATALOG_ROOT/$source_rel"
    done
  fi
  if [[ -f "$TARGET/$LOCAL_REL" ]] && [[ -s "$TARGET/$LOCAL_REL" ]]; then
    printf '\n\n# Repository-specific instructions\n\nThese project instructions supplement but do not silently weaken the secure-development baseline.\n\n'
    emit_trimmed_file "$TARGET/$LOCAL_REL"
  fi
  printf '\n'
} > "$core_output"

if [[ "$MODE" == "path-specific" ]]; then
  mkdir -p -- "$STAGE/.github/instructions"
  for module_id in "${PATH_IDS[@]}"; do
    source_rel="$(jq -r --arg id "$module_id" '.modules[] | select(.id == $id) | .path' "$CATALOG_FILE")"
    destination="$STAGE/.github/instructions/$module_id.instructions.md"
    {
      extract_frontmatter "$CATALOG_ROOT/$source_rel"
      printf '\n\n%s %s. Modules: %s. Do not edit; regenerate. -->\n\n' "$MARKER_PREFIX" "$catalog_version" "$module_id"
      extract_body "$CATALOG_ROOT/$source_rel"
      printf '\n'
    } > "$destination"
  done
fi

while IFS= read -r -d '' review_source; do
  review_rel="${review_source#"$REVIEW_ROOT"/}"
  mkdir -p -- "$(dirname -- "$STAGE/$review_rel")"
  cp -- "$review_source" "$STAGE/$review_rel"
done < <(find "$REVIEW_ROOT" -type f -print0)

mapfile -t MANAGED_RELS < <(cd -- "$STAGE" && find . -type f ! -path "./$STATE_REL" -print | sed 's#^\./##' | sort)

write_json_array() {
  local indent="$1"; shift
  local -a values=("$@")
  local index comma
  printf '['
  if ((${#values[@]})); then
    printf '\n'
    for index in "${!values[@]}"; do
      comma=','; ((index == ${#values[@]} - 1)) && comma=''
      printf '%s  "%s"%s\n' "$indent" "${values[$index]}" "$comma"
    done
    printf '%s' "$indent"
  fi
  printf ']'
}

state_output="$STAGE/$STATE_REL"
mkdir -p -- "$(dirname -- "$state_output")"
{
  printf '{\n'
  printf '  "catalogVersion": "%s",\n' "$catalog_version"
  printf '  "generator": "Skills Hub",\n'
  printf '  "managedFiles": '
  write_json_array '  ' "${MANAGED_RELS[@]}"
  printf ',\n  "mode": "%s",\n' "$MODE"
  printf '  "modules": '
  write_json_array '  ' "${SELECTED_IDS[@]}"
  printf ',\n  "preset": "%s",\n' "$PRESET"
  printf '  "reviewPack": true,\n'
  printf '  "schemaVersion": 1\n'
  printf '}\n'
} > "$state_output"

mapfile -t OUTPUT_RELS < <(cd -- "$STAGE" && find . -type f -print | sed 's#^\./##' | sort)

is_generated() {
  local path="$1"
  grep -Fq -- "$MARKER_PREFIX" "$path" 2>/dev/null || grep -Fq -- '"generator": "Skills Hub"' "$path" 2>/dev/null
}

assert_safe_output_path() {
  local relative="$1"
  local current="$TARGET"
  local part
  [[ "$relative" == .github/* && "$relative" != *'..'* ]] || fail "Unsafe managed path: $relative"
  IFS='/' read -r -a path_parts <<< "$relative"
  for part in "${path_parts[@]}"; do
    current="$current/$part"
    [[ ! -L "$current" ]] || fail "Refusing to follow symlink in generated path: $current"
  done
}

declare -a WRITES=()
declare -a STALE=()
declare -a UNCHANGED=()
for relative in "${OUTPUT_RELS[@]}"; do
  assert_safe_output_path "$relative"
  destination="$TARGET/$relative"
  if [[ -e "$destination" ]]; then
    if cmp -s -- "$STAGE/$relative" "$destination"; then
      UNCHANGED+=("$relative")
      continue
    fi
    if ! $FORCE && ! is_generated "$destination"; then
      fail "Refusing to overwrite non-Skills-Hub file: $destination. Merge it manually or rerun with --force."
    fi
  fi
  WRITES+=("$relative")
done

if [[ -f "$TARGET/$STATE_REL" ]]; then
  jq empty "$TARGET/$STATE_REL" >/dev/null 2>&1 || fail "Cannot parse generated state: $TARGET/$STATE_REL"
  while IFS= read -r relative; do
    [[ -n "$relative" ]] || continue
    wanted_output=false
    for output_rel in "${OUTPUT_RELS[@]}"; do [[ "$relative" == "$output_rel" ]] && wanted_output=true && break; done
    $wanted_output && continue
    assert_safe_output_path "$relative"
    destination="$TARGET/$relative"
    if [[ -e "$destination" ]]; then
      is_generated "$destination" || fail "Refusing to remove modified generated file: $destination"
      STALE+=("$relative")
    fi
  done < <(jq -r '.managedFiles[]?' "$TARGET/$STATE_REL")
fi

printf 'Target: %s\n' "$TARGET"
printf 'Mode: %s; preset: %s\n' "$MODE" "$PRESET"
printf 'Modules (%s): %s\n' "${#SELECTED_IDS[@]}" "$selected_csv"
printf 'Review pack: enabled\n'

if $CHECK; then
  if ((${#WRITES[@]} || ${#STALE[@]})); then
    for relative in "${WRITES[@]}"; do printf 'DRIFT write %s\n' "$relative"; done
    for relative in "${STALE[@]}"; do printf 'DRIFT remove %s\n' "$relative"; done
    exit 1
  fi
  printf 'Up to date (%s files).\n' "${#UNCHANGED[@]}"
  exit 0
fi

if $DRY_RUN; then
  for relative in "${WRITES[@]}"; do printf 'WOULD WRITE %s\n' "$relative"; done
  for relative in "${STALE[@]}"; do printf 'WOULD REMOVE %s\n' "$relative"; done
  ((${#WRITES[@]} || ${#STALE[@]})) || printf 'No changes.\n'
  exit 0
fi

for relative in "${WRITES[@]}"; do
  destination="$TARGET/$relative"
  mkdir -p -- "$(dirname -- "$destination")"
  temporary="$(mktemp "$(dirname -- "$destination")/.skills-hub.XXXXXX")"
  cp -- "$STAGE/$relative" "$temporary"
  mv -f -- "$temporary" "$destination"
  printf 'WROTE %s\n' "$relative"
done
for relative in "${STALE[@]}"; do
  rm -f -- "$TARGET/$relative"
  printf 'REMOVED %s\n' "$relative"
done
((${#WRITES[@]} || ${#STALE[@]})) || printf 'No changes.\n'
