import { readFile } from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';

export const COPILOT = 'plugins/ai-security-hub';
export const CLAUDE = 'claude-plugins/ai-security-hub';
export const SKILLS = ['secure-development', 'secure-code-review-method'];
export const MARKER = '<!-- Generated by AI Security Hub';
const FALLBACK = 'If the current change set is unavailable through the configured read-only tools, ask the user to attach a diff or name the files to review. Do not run Git, a shell, or a target-provided command to obtain it.';

export function frontmatter(text) {
  const match = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!match) throw new Error('Markdown requires YAML frontmatter');
  return { attributes: yaml.load(match[1]), body: text.slice(match[0].length).trimStart() };
}
export function markdown(attributes, body) {
  return `---\n${yaml.dump(attributes, { lineWidth: -1, noRefs: true })}---\n\n${body.trim()}\n`;
}
const json = value => JSON.stringify(value, null, 2) + '\n';
const read = async (root, file) => (await readFile(path.join(root, file), 'utf8')).replaceAll('\r\n', '\n');

function remapGuidance(text) {
  // The review skill lives beside secure-development in every distribution.
  return text.replaceAll('../../com.github.copilot/rules/', '../secure-development/references/')
    .replaceAll('../../../com.github.copilot/rules/', '../../secure-development/references/');
}

function hook(output, prefix, message, dialect, token) {
  const nested = { hookEventName: 'SessionStart', additionalContext: message };
  const payload = dialect === 'copilot'
    ? { additionalContext: message, hookSpecificOutput: nested }
    : { hookSpecificOutput: nested };
  const literal = JSON.stringify(payload);
  output.set(`${prefix}/session-start.sh`, `#!/bin/sh\n# Generated by AI Security Hub. Do not edit.\nprintf '%s\\n' '${literal.replaceAll("'", "'\"'\"'")}'\n`);
  output.set(`${prefix}/session-start.ps1`, `# Generated by AI Security Hub. Do not edit.\nWrite-Output '${literal.replaceAll("'", "''")}'\n`);
  const relative = dialect === 'native' ? 'com.github.copilot/hooks' : 'hooks';
  const command = `sh "\${${token}}/${relative}/session-start.sh"`;
  const windows = `powershell -NoProfile -NonInteractive -File "\${${token}}/${relative}/session-start.ps1"`;
  const entry = dialect === 'claude'
    ? { hooks: [{ type: 'command', command, timeout: 5 }] }
    : { type: 'command', command, windows, ...(dialect === 'copilot' ? { bash: command, powershell: windows } : {}), timeout: 5 };
  output.set(`${prefix}/hooks.json`, json({ hooks: { SessionStart: [entry] } }));
}

export async function addMarketplaces(root, manifest, output) {
  const catalog = JSON.parse(await read(root, 'catalog/catalog.json'));
  const guide = 'skills/secure-development';
  output.set(`${guide}/SKILL.md`, await read(root, 'plugin/skills/secure-development/SKILL.md'));
  const index = [];
  for (const module of catalog.modules) {
    const rule = output.get(`com.github.copilot/rules/${module.id}.instructions.md`);
    output.set(`${guide}/references/${module.id}.instructions.md`, rule);
    index.push({ id: module.id, description: module.description,
      applyTo: frontmatter(rule).attributes.applyTo, path: `references/${module.id}.instructions.md` });
  }
  output.set(`${guide}/references/modules.json`, json(index));
  for (const [file, text] of [...output]) {
    if (file.startsWith('skills/secure-code-review-method/')) output.set(file, remapGuidance(text));
  }

  const nativeAgent = frontmatter(output.get('com.github.copilot/agents/secure-code-review.agent.md'));
  const portableBody = nativeAgent.body
    .replaceAll('../rules/', '../skills/secure-development/references/')
    .replaceAll('../../skills/', '../skills/')
    .replace('Use only the configured read-only search, usage, change, and problem tools.', 'Use only the configured file-reading and search tools.')
    + `\n${FALLBACK}\n`;
  const portableAttributes = { ...nativeAgent.attributes,
    description: 'Use only when the user explicitly requests a read-only security review or validation of a security finding.',
    tools: ['read', 'search'] };
  delete portableAttributes.target;
  const portableAgent = markdown(portableAttributes, portableBody);
  output.set('agents/secure-code-review.agent.md', portableAgent);

  const metadata = { ...manifest };
  delete metadata.$schema;
  delete metadata.extensions;
  const copilotManifest = { ...metadata, agents: ['./agents/secure-code-review.md'],
    skills: SKILLS.map(name => `./skills/${name}/`), commands: './commands/',
    rules: './rules/', hooks: './hooks/hooks.json' };
  output.set(`${COPILOT}/.github/plugin/plugin.json`, json(copilotManifest));
  // Current clients discover this root manifest; the sidecar serves the company tooling.
  output.set(`${COPILOT}/plugin.json`, json(copilotManifest));
  output.set(`${COPILOT}/agents/secure-code-review.md`, portableAgent);
  const claudeAttributes = { name: 'secure-code-review',
    description: 'Use only when the user explicitly requests a read-only security review or validation of a security finding.',
    tools: 'Read, Grep, Glob', disallowedTools: 'Bash, Edit, Write, NotebookEdit',
    model: 'inherit' };
  output.set(`${CLAUDE}/agents/secure-code-review.md`, markdown(claudeAttributes, portableBody));

  for (const [file, text] of [...output]) {
    if (file.startsWith('skills/')) {
      output.set(`${COPILOT}/${file}`, text);
      output.set(`${CLAUDE}/${file}`, text);
    }
    if (file.startsWith('com.github.copilot/rules/')) {
      output.set(`${COPILOT}/${file.replace('com.github.copilot/', '')}`, text);
    }
    if (file.startsWith('com.github.copilot/commands/')) {
      const name = path.posix.basename(file, '.md');
      const { attributes, body } = frontmatter(text);
      const commandBody = body.replace(/\$\{input:[^}]+\}/g, '$ARGUMENTS')
        .replaceAll('../../skills/', '../skills/') + `\n${FALLBACK}\n`;
      output.set(`${COPILOT}/commands/${name}.md`, markdown(attributes, commandBody));
      // The company translator consumes prompts/; Copilot loads commands/ via its manifest.
      output.set(`${COPILOT}/prompts/${name}.prompt.md`, markdown(attributes, commandBody));
      output.set(`${CLAUDE}/commands/${name}.md`, markdown({
        description: attributes.description, 'argument-hint': attributes['argument-hint'],
        context: 'fork', agent: 'ai-security-hub:secure-code-review',
        'allowed-tools': 'Read, Grep, Glob', 'disable-model-invocation': true,
      }, commandBody));
    }
  }
  const commands = [...output.keys()].filter(file => file.startsWith(`${CLAUDE}/commands/`))
    .map(file => './' + file.slice(CLAUDE.length + 1));
  output.set(`${CLAUDE}/.claude-plugin/plugin.json`, json({ ...metadata,
    agents: ['./agents/secure-code-review.md'], skills: SKILLS.map(name => `./skills/${name}`),
    commands })); // Claude auto-loads hooks/hooks.json; listing it again duplicates hooks.

  const { message } = JSON.parse(await read(root, 'plugin/hooks/reminder.json'));
  if (typeof message !== 'string' || !message.trim()) throw new Error('Hook reminder must be non-empty');
  hook(output, 'com.github.copilot/hooks', message, 'native', 'PLUGIN_ROOT');
  hook(output, `${COPILOT}/hooks`, message, 'copilot', 'CLAUDE_PLUGIN_ROOT');
  // The reference translator accepts bare script paths, while client runtimes need
  // plugin-root-qualified commands. The runtime manifest loads only hooks/hooks.json.
  output.set(`${COPILOT}/hooks/copilot-agents-source.json`, json({ hooks: { SessionStart: [
    { type: 'command', bash: './hooks/session-start.sh', timeoutSec: 5 },
  ] } }));
  hook(output, `${CLAUDE}/hooks`, message, 'claude', 'CLAUDE_PLUGIN_ROOT');

  const installation = await read(root, 'docs/PLUGIN.md');
  const changelog = await read(root, 'CHANGELOG.md');
  for (const prefix of [COPILOT, CLAUDE]) {
    output.set(`${prefix}/README.md`, `${MARKER}. Do not edit; regenerate. -->\n\n${installation}`);
    output.set(`${prefix}/CHANGELOG.md`, `${MARKER}. Do not edit; regenerate. -->\n\n${changelog}`);
  }
  for (const [file, name, source] of [
    ['.github/plugin/marketplace.json', 'ai-security-hub-marketplace', COPILOT],
    ['.claude-plugin/marketplace.json', 'ai-security-hub-claude', CLAUDE],
  ]) output.set(file, json({ name, owner: manifest.author,
    metadata: { description: manifest.description, version: manifest.version },
    plugins: [{ name: manifest.name, description: manifest.description, version: manifest.version, source: `./${source}` }] }));
}

export function marketplaceExport(output) {
  // Workspace-only .github customizations are deliberately absent from this export.
  return new Map([...output].filter(([file]) => file.startsWith('agents/') || file.startsWith('skills/') ||
    file.startsWith('plugins/') || file.startsWith('claude-plugins/') ||
    file === '.github/plugin/marketplace.json' || file === '.claude-plugin/marketplace.json'));
}
