#!/usr/bin/env node
// Build the installable plugin from the same sources as the repository installer.
// Maintainers install build dependencies; consumers load the committed packages.
import { chmod, lstat, mkdir, mkdtemp, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { addMarketplaces, marketplaceExport, COPILOT, CLAUDE } from './marketplace.mjs';

const ROOT = fileURLToPath(new URL('../', import.meta.url));
const NAMESPACE = 'com.github.copilot';
const GENERATED = ['skills', 'agents', NAMESPACE, 'plugins', 'claude-plugins'];
const MARKER = '<!-- Generated by AI Security Hub';
const SCHEMA = 'https://agent-plugins.org/schemas/1.0.0/plugin.schema.json';

async function read(root, relative) {
  return (await readFile(path.join(root, relative), 'utf8')).replaceAll('\r\n', '\n');
}

async function files(root, relative) {
  const absolute = path.join(root, relative);
  const stat = await lstat(absolute).catch(error => {
    if (error.code === 'ENOENT') return undefined;
    throw error;
  });
  if (!stat) return [];
  if (stat.isSymbolicLink()) throw new Error(`Symlinks are not supported in plugin content: ${relative}`);
  if (stat.isFile()) return [relative];
  const children = await readdir(absolute);
  const nested = await Promise.all(children.sort().map(child => files(root, `${relative}/${child}`)));
  return nested.flat();
}

function relocateLinks(content, source, destination, locations) {
  return content.replace(/\]\(([^)]+)\)/g, (match, target) => {
    if (/^(?:[a-z]+:|#)/i.test(target)) return match;
    const oldPath = path.posix.normalize(path.posix.join(path.posix.dirname(source), target));
    const newPath = locations.get(oldPath);
    if (!newPath) throw new Error(`Unmapped review-pack link in ${source}: ${target}`);
    return `](${path.posix.relative(path.posix.dirname(destination), newPath)}${target.endsWith('/') ? '/' : ''})`;
  });
}

export async function collectPlugin(root = ROOT) {
  const manifest = JSON.parse(await read(root, 'plugin.json'));
  const catalog = JSON.parse(await read(root, 'catalog/catalog.json'));
  if (manifest.$schema !== SCHEMA || manifest.name !== 'ai-security-hub' ||
      !/^\d+\.\d+\.\d+$/.test(manifest.version)) {
    throw new Error('plugin.json must declare Agent Plugins 1.0 and an ai-security-hub X.Y.Z version');
  }
  const allowed = ['$schema', 'name', 'version', 'description', 'author', 'homepage', 'repository', 'license', 'keywords', 'extensions'];
  if (Object.keys(manifest).some(key => !allowed.includes(key))) {
    throw new Error('plugin.json contains unsupported Agent Plugins manifest fields');
  }
  const output = new Map();
  for (const module of catalog.modules) {
    const content = await read(root, `catalog/${module.path}`);
    const rule = module.kind === 'repository'
      ? `---\napplyTo: "**"\nalwaysApply: true\n---\n\n${MARKER} ${catalog.catalogVersion}. Do not edit; regenerate. -->\n\n${content}`
      : content.replace(/^(---\n[\s\S]*?\n---\n)/, `$1\n${MARKER} ${catalog.catalogVersion}. Do not edit; regenerate. -->\n`);
    output.set(`${NAMESPACE}/rules/${module.id}.instructions.md`, rule);
  }

  const reviewRoot = 'review-pack/.github';
  const locations = new Map([
    [`${reviewRoot}/copilot-instructions.md`, `${NAMESPACE}/rules/core.instructions.md`],
    [`${reviewRoot}/instructions/`, `${NAMESPACE}/rules`],
    [`${reviewRoot}/instructions`, `${NAMESPACE}/rules`],
  ]);
  const reviewFiles = await files(root, reviewRoot);
  for (const source of reviewFiles) {
    const relative = source.slice(reviewRoot.length + 1);
    const destination = relative.startsWith('skills/') ? relative
      : relative.startsWith('prompts/')
        ? `${NAMESPACE}/${relative.replace(/^prompts\//, 'commands/').replace(/\.prompt\.md$/, '.md')}`
        : `${NAMESPACE}/${relative}`;
    locations.set(source, destination);
  }
  for (const source of reviewFiles) {
    const destination = locations.get(source);
    output.set(destination, relocateLinks(await read(root, source), source, destination, locations));
  }

  await addMarketplaces(root, manifest, output);
  return { manifest, output };
}

export async function buildPlugin(root = ROOT, check = false) {
  const { manifest, output } = await collectPlugin(root);
  const existing = (await Promise.all(GENERATED.map(dir => files(root, dir)))).flat();
  // Inspect the parent as well so writes cannot follow a linked marketplace directory.
  await files(root, '.github/plugin');
  await files(root, '.claude-plugin');
  const stale = existing.filter(file => !output.has(file));
  const changed = [];
  for (const [file, content] of output) {
    const actual = await readFile(path.join(root, file), 'utf8').catch(error => {
      if (error.code === 'ENOENT') return undefined;
      throw error;
    });
    if (actual !== content) changed.push(file);
  }
  if (check && (stale.length || changed.length)) {
    throw new Error(`Plugin output has drifted. Run node scripts/plugin.mjs build.\n${[...changed, ...stale].join('\n')}`);
  }
  if (!check) {
    for (const file of [...stale, ...changed.filter(file => existing.includes(file))]) {
      if (file.endsWith('.md') && !(await read(root, file)).includes(MARKER)) {
        throw new Error(`Refusing to replace an unmanaged file: ${file}`);
      }
    }
    for (const file of changed) {
      await mkdir(path.dirname(path.join(root, file)), { recursive: true });
      await writeFile(path.join(root, file), output.get(file));
      if (file.endsWith('.sh')) await chmod(path.join(root, file), 0o755);
    }
    for (const file of stale) await rm(path.join(root, file));
  }
  return { manifest, output };
}

export async function packagePlugin(root = ROOT, target = 'native') {
  const { manifest, output } = await buildPlugin(root, true);
  const staging = await mkdtemp(path.join(tmpdir(), 'ai-security-hub-plugin-'));
  if (!['native', 'copilot', 'claude', 'marketplace'].includes(target)) throw new Error(`Unknown package target: ${target}`);
  const stem = `${manifest.name}-${target}-${manifest.version}`;
  const artifact = path.join(root, 'dist', `${stem}.tar.gz`);
  try {
    const prefix = target === 'copilot' ? COPILOT : CLAUDE;
    const bundle = target === 'marketplace' ? marketplaceExport(output) : new Map([...output].filter(([file]) => target === 'native'
      ? file.startsWith('skills/') || file.startsWith(`${NAMESPACE}/`)
      : file.startsWith(`${prefix}/`)).map(([file, text]) => [target === 'native' ? file : file.slice(prefix.length + 1), text]));
    if (target === 'native') {
      bundle.set('plugin.json', await read(root, 'plugin.json'));
      bundle.set('README.md', await read(root, 'docs/PLUGIN.md'));
      bundle.set('CHANGELOG.md', await read(root, 'CHANGELOG.md'));
    }
    for (const [file, content] of bundle) {
      const destination = path.join(staging, stem, file);
      await mkdir(path.dirname(destination), { recursive: true });
      await writeFile(destination, content);
      if (file.endsWith('.sh')) await chmod(destination, 0o755);
    }
    await mkdir(path.dirname(artifact), { recursive: true });
    const packed = path.join(staging, `${stem}.tar.gz`);
    const result = spawnSync('tar', ['-czf', packed, '-C', staging, stem], { encoding: 'utf8' });
    if (result.error || result.status !== 0) {
      throw new Error(`Packaging requires tar on PATH: ${result.error?.message ?? result.stderr}`);
    }
    const bytes = await readFile(packed);
    await writeFile(artifact, bytes);
    const digest = createHash('sha256').update(bytes).digest('hex');
    await writeFile(`${artifact}.sha256`, `${digest}  ${path.basename(artifact)}\n`);
    return artifact;
  } finally {
    await rm(staging, { recursive: true, force: true });
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    const [command, ...extra] = process.argv.slice(2);
    if (extra.length || !['build', 'check', 'package'].includes(command)) {
      throw new Error('Usage: node scripts/plugin.mjs build|check|package');
    }
    if (command === 'package') {
      for (const target of ['native', 'copilot', 'claude', 'marketplace']) console.log(await packagePlugin(ROOT, target));
    }
    else {
      const { manifest, output } = await buildPlugin(ROOT, command === 'check');
      console.log(`${command === 'check' ? 'Checked' : 'Built'} ${manifest.name} ${manifest.version}: ${output.size} generated files.`);
    }
  } catch (error) {
    console.error(`error: ${error.message}`);
    process.exitCode = 1;
  }
}
