#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
CATALOG_ROOT="$REPO_ROOT/catalog"
CATALOG_FILE="$CATALOG_ROOT/catalog.json"
REVIEW_ROOT="$REPO_ROOT/review-pack/.github"
MAX_MODULE_WORDS=500
MARKER_PREFIX="<!-- Generated by AI Security Hub"
declare -a ERRORS=()
declare -A IDS=()
declare -A PATHS=()
declare -A REPRESENTED=()

error() { ERRORS+=("$*"); }

command -v jq >/dev/null 2>&1 || { printf 'ERROR Required command not found: jq\n' >&2; exit 1; }
if ! jq empty "$CATALOG_FILE" >/dev/null 2>&1; then
  printf 'ERROR Cannot parse %s\n' "$CATALOG_FILE"
  exit 1
fi

schema_version="$(jq -r '.schemaVersion // empty' "$CATALOG_FILE")"
[[ "$schema_version" == "1" ]] || error "catalog schemaVersion must be 1"
catalog_version="$(jq -r '.catalogVersion // empty' "$CATALOG_FILE")"
[[ "$catalog_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || error "catalogVersion must use semantic X.Y.Z form"

module_count="$(jq '.modules | if type == "array" then length else 0 end' "$CATALOG_FILE")"
((module_count > 0)) || error "catalog modules must be a non-empty list"

extract_body() {
  awk '
    NR == 1 && $0 == "---" { in_fm=1; next }
    in_fm && $0 == "---" { in_fm=0; next }
    in_fm { next }
    !started && $0 == "" { next }
    { print; started=1 }
  ' "$1"
}

for ((index=0; index<module_count; index++)); do
  prefix="modules[$index]"
  module_id="$(jq -r ".modules[$index].id // empty" "$CATALOG_FILE")"
  if [[ ! "$module_id" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
    error "$prefix.id must be lowercase kebab-case"
    continue
  fi
  [[ -z "${IDS[$module_id]:-}" ]] || error "duplicate module id: $module_id"
  IDS[$module_id]=1

  relative="$(jq -r ".modules[$index].path // empty" "$CATALOG_FILE")"
  if [[ -z "$relative" ]]; then error "$module_id: path is required"; continue; fi
  [[ -z "${PATHS[$relative]:-}" ]] || error "duplicate module path: $relative"
  PATHS[$relative]=1
  if [[ "$relative" == /* || "$relative" == *'..'* ]]; then error "$module_id: unsafe path $relative"; continue; fi
  source="$CATALOG_ROOT/$relative"
  REPRESENTED[$relative]=1
  if [[ ! -f "$source" ]]; then error "$module_id: missing source $source"; continue; fi

  kind="$(jq -r ".modules[$index].kind // empty" "$CATALOG_FILE")"
  [[ "$kind" == "repository" || "$kind" == "path" ]] || error "$module_id: kind must be repository or path"
  group="$(jq -r ".modules[$index].group // empty" "$CATALOG_FILE")"
  [[ -n "$group" ]] || error "$module_id: group is required"
  description="$(jq -r ".modules[$index].description // empty" "$CATALOG_FILE")"
  description_words="$(printf '%s' "$description" | wc -w | tr -d ' ')"
  ((description_words >= 3)) || error "$module_id: meaningful description is required"
  grep -q $'\r' "$source" && error "$module_id: use LF line endings"
  word_count="$(wc -w < "$source" | tr -d ' ')"
  ((word_count <= MAX_MODULE_WORDS)) || error "$module_id: $word_count words exceeds $MAX_MODULE_WORDS"

  if [[ "$kind" == "path" ]]; then
    [[ "$relative" == *.instructions.md ]] || error "$module_id: path module filename must end .instructions.md"
    [[ "$(head -n 1 "$source")" == "---" ]] || error "$module_id: path-specific module lacks frontmatter"
    closing_line="$(awk 'NR > 1 && $0 == "---" { print NR; exit }' "$source")"
    [[ -n "$closing_line" ]] || { error "$module_id: path-specific module has unterminated frontmatter"; continue; }
    mapfile -t fields < <(sed -n "2,$((closing_line - 1))p" "$source" | sed '/^[[:space:]]*$/d')
    apply_count=0
    for field in "${fields[@]}"; do
      if [[ "$field" == applyTo:* ]]; then
        ((apply_count += 1))
        if [[ ! "$field" =~ ^applyTo:\ \"[^\"]+\"$ && ! "$field" =~ ^applyTo:\ \'[^\']+\'$ ]]; then
          error "$module_id: applyTo must be a quoted, non-empty value"
        fi
      elif [[ "$field" != excludeAgent:* ]]; then
        error "$module_id: unsupported frontmatter field: $field"
      fi
    done
    ((apply_count == 1)) || error "$module_id: frontmatter must contain one quoted applyTo field"
    first_body="$(extract_body "$source" | sed -n '1p')"
    [[ "$first_body" == '# '* ]] || error "$module_id: body must begin with an H1 title"
    bullet_count="$(extract_body "$source" | grep -c '^- ' || true)"
    ((bullet_count >= 5)) || error "$module_id: include at least five actionable instructions"
  elif [[ "$(head -n 1 "$source")" == "---" ]]; then
    error "$module_id: repository module must not have path frontmatter"
  fi

  if jq -e ".modules[$index].detect != null" "$CATALOG_FILE" >/dev/null; then
    has_files="$(jq ".modules[$index].detect.files // [] | length" "$CATALOG_FILE")"
    has_content="$(jq ".modules[$index].detect.content // [] | length" "$CATALOG_FILE")"
    ((has_files > 0 || has_content > 0)) || error "$module_id: detect must contain files or content rules"
    for ((rule=0; rule<has_content; rule++)); do
      rule_files="$(jq ".modules[$index].detect.content[$rule].files // [] | length" "$CATALOG_FILE")"
      rule_needles="$(jq ".modules[$index].detect.content[$rule].needles // [] | length" "$CATALOG_FILE")"
      ((rule_files > 0 && rule_needles > 0)) || error "$module_id: every content detector needs files and needles"
    done
  fi
done

while IFS= read -r source; do
  relative="${source#"$CATALOG_ROOT"/}"
  [[ "$(basename -- "$source")" == "README.md" ]] && continue
  [[ -n "${REPRESENTED[$relative]:-}" ]] || error "catalog markdown not listed in catalog.json: $relative"
done < <(find "$CATALOG_ROOT" -type f -name '*.md' | sort)

[[ -n "${IDS[core]:-}" ]] || error "catalog must contain the core module"

preset_tmp="$(mktemp -d)"
cleanup() { rm -rf -- "$preset_tmp"; }
trap cleanup EXIT
while IFS= read -r preset; do
  if ! "$SCRIPT_DIR/build.sh" --target "$preset_tmp" --preset "$preset" --no-detect --dry-run >/dev/null 2>&1; then
    error "preset '$preset' cannot be resolved or does not include core"
  fi
done < <(jq -r '.presets | keys[]' "$CATALOG_FILE")

expected_review_files=(
  agents/secure-code-review.agent.md
  prompts/secure-code-review.prompt.md
  prompts/review-security-changes.prompt.md
  prompts/validate-security-finding.prompt.md
  skills/secure-code-review-method/SKILL.md
  skills/secure-code-review-method/references/workflow.md
  skills/secure-code-review-method/references/evidence-and-validation.md
  skills/secure-code-review-method/references/review-coverage.md
  skills/secure-code-review-method/references/report-template.md
)
for relative in "${expected_review_files[@]}"; do
  path="$REVIEW_ROOT/$relative"
  [[ -f "$path" ]] || { error "review pack missing $relative"; continue; }
  grep -Fq "$MARKER_PREFIX" "$path" 2>/dev/null || error "review pack file lacks generated marker: $relative"
  grep -q $'\r' "$path" && error "review pack file must use LF line endings: $relative"
done

agent="$REVIEW_ROOT/agents/secure-code-review.agent.md"
for tool in search/changes search/codebase read/problems search/usages; do
  grep -Fq "'$tool'" "$agent" || error "review agent is missing read-only tool $tool"
done
if grep -Eq "(terminal|execute|edit/|web/fetch|mcp-servers)" <(awk 'NR == 1 && $0 == "---" { next } $0 == "---" { exit } { print }' "$agent"); then
  error "review agent frontmatter contains a non-read-only tool or server"
fi
grep -Fq 'target: vscode' "$agent" || error "review agent must target vscode"
grep -Fq 'disable-model-invocation: true' "$agent" || error "review agent must not be invoked automatically as a subagent"

for prompt in "$REVIEW_ROOT"/prompts/*.prompt.md; do
  grep -Fq 'agent: Secure Code Review' "$prompt" || error "review prompt must use the Secure Code Review agent: $(basename -- "$prompt")"
done
skill="$REVIEW_ROOT/skills/secure-code-review-method/SKILL.md"
grep -Fq 'name: secure-code-review-method' "$skill" || error "review skill name must match its directory"
grep -Fq 'user-invocable: false' "$skill" || error "review method skill must remain hidden from the slash menu"
grep -Fq 'disable-model-invocation: true' "$skill" || error "review method skill must not load outside an explicit review surface"

if find "$SCRIPT_DIR" "$REPO_ROOT/tests" -type f -name '*.py' -print -quit | grep -q .; then
  error "Python source remains under scripts/ or tests/"
fi

if ((${#ERRORS[@]})); then
  for message in "${ERRORS[@]}"; do printf 'ERROR %s\n' "$message"; done
  printf 'Validation failed with %s error(s).\n' "${#ERRORS[@]}" >&2
  exit 1
fi

preset_count="$(jq '.presets | length' "$CATALOG_FILE")"
review_count="$(find "$REVIEW_ROOT" -type f | wc -l | tr -d ' ')"
printf 'Validated %s modules, %s presets, and %s review-pack files.\n' "$module_count" "$preset_count" "$review_count"
