[CmdletBinding()]
param()

Set-StrictMode -Version 2.0
$ErrorActionPreference = "Stop"

$RepoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot ".."))
$CatalogRoot = Join-Path $RepoRoot "catalog"
$CatalogFile = Join-Path $CatalogRoot "catalog.json"
$ReviewRoot = Join-Path $RepoRoot "review-pack/.github"
$MarkerPrefix = "<!-- Generated by Skills Hub"
$MaxModuleWords = 500
$Errors = New-Object 'System.Collections.Generic.List[string]'

function Add-ValidationError([string]$Message) { $Errors.Add($Message) }

function Normalize-Lf([string]$Text) {
    return $Text.Replace("`r`n", "`n").Replace("`r", "`n")
}

function Get-ObjectProperty($Object, [string]$Name) {
    if ($null -eq $Object) { return $null }
    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) { return $null }
    return $property.Value
}

function Get-WordCount([string]$Text) {
    if (-not $Text.Trim()) { return 0 }
    return @([Regex]::Split($Text.Trim(), '\s+') | Where-Object { $_ }).Count
}

try {
    if (-not (Test-Path -LiteralPath $CatalogFile -PathType Leaf)) { throw "Cannot find $CatalogFile" }
    try { $catalog = ConvertFrom-Json ([IO.File]::ReadAllText($CatalogFile)) } catch { throw "Cannot parse ${CatalogFile}: $($_.Exception.Message)" }

    if ([string](Get-ObjectProperty $catalog "schemaVersion") -ne "1") { Add-ValidationError "catalog schemaVersion must be 1" }
    $catalogVersion = [string](Get-ObjectProperty $catalog "catalogVersion")
    if ($catalogVersion -notmatch '^\d+\.\d+\.\d+$') { Add-ValidationError "catalogVersion must use semantic X.Y.Z form" }

    $modules = @(Get-ObjectProperty $catalog "modules")
    if ($modules.Count -eq 0) { Add-ValidationError "catalog modules must be a non-empty list" }
    $ids = @{}
    $paths = @{}
    $represented = @{}
    $moduleMap = @{}

    for ($index = 0; $index -lt $modules.Count; $index++) {
        $module = $modules[$index]
        $prefix = "modules[$index]"
        $moduleId = [string](Get-ObjectProperty $module "id")
        if ($moduleId -notmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$') {
            Add-ValidationError "$prefix.id must be lowercase kebab-case"
            continue
        }
        if ($ids.ContainsKey($moduleId)) { Add-ValidationError "duplicate module id: $moduleId" }
        $ids[$moduleId] = $true
        $moduleMap[$moduleId] = $module

        $relative = [string](Get-ObjectProperty $module "path")
        if (-not $relative) { Add-ValidationError "${moduleId}: path is required"; continue }
        if ($paths.ContainsKey($relative)) { Add-ValidationError "duplicate module path: $relative" }
        $paths[$relative] = $true
        if ([IO.Path]::IsPathRooted($relative) -or @($relative -split '/') -contains "..") {
            Add-ValidationError "${moduleId}: unsafe path $relative"
            continue
        }
        $represented[$relative] = $true
        $source = Join-Path $CatalogRoot $relative
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { Add-ValidationError "${moduleId}: missing source $source"; continue }

        $kind = [string](Get-ObjectProperty $module "kind")
        if ($kind -ne "repository" -and $kind -ne "path") { Add-ValidationError "${moduleId}: kind must be repository or path" }
        $group = [string](Get-ObjectProperty $module "group")
        if (-not $group) { Add-ValidationError "${moduleId}: group is required" }
        $description = [string](Get-ObjectProperty $module "description")
        if ((Get-WordCount $description) -lt 3) { Add-ValidationError "${moduleId}: meaningful description is required" }

        $rawText = [IO.File]::ReadAllText($source)
        if ($rawText.Contains("`r")) { Add-ValidationError "${moduleId}: use LF line endings" }
        $text = Normalize-Lf $rawText
        $wordCount = Get-WordCount $text
        if ($wordCount -gt $MaxModuleWords) { Add-ValidationError "${moduleId}: $wordCount words exceeds $MaxModuleWords" }

        if ($kind -eq "path") {
            if (-not $relative.EndsWith(".instructions.md", [StringComparison]::Ordinal)) { Add-ValidationError "${moduleId}: path module filename must end .instructions.md" }
            if (-not $text.StartsWith("---`n", [StringComparison]::Ordinal)) {
                Add-ValidationError "${moduleId}: path-specific module lacks frontmatter"
                continue
            }
            $closing = $text.IndexOf("`n---`n", 4, [StringComparison]::Ordinal)
            if ($closing -lt 0) { Add-ValidationError "${moduleId}: path-specific module has unterminated frontmatter"; continue }
            $frontmatter = $text.Substring(4, $closing - 4)
            $body = $text.Substring($closing + 5).TrimStart("`n")
            $fields = @($frontmatter -split "`n" | Where-Object { $_.Trim() })
            $applyLines = @($fields | Where-Object { $_.StartsWith("applyTo:", [StringComparison]::Ordinal) })
            if ($applyLines.Count -ne 1 -or $applyLines[0] -notmatch '^applyTo: (["'']).+\1$') {
                Add-ValidationError "${moduleId}: frontmatter must contain one quoted applyTo field"
            }
            foreach ($field in $fields) {
                if (-not $field.StartsWith("applyTo:", [StringComparison]::Ordinal) -and -not $field.StartsWith("excludeAgent:", [StringComparison]::Ordinal)) {
                    Add-ValidationError "${moduleId}: unsupported frontmatter field: $field"
                }
            }
            if (-not $body.StartsWith("# ", [StringComparison]::Ordinal)) { Add-ValidationError "${moduleId}: body must begin with an H1 title" }
            $bulletCount = @($body -split "`n" | Where-Object { $_.StartsWith("- ", [StringComparison]::Ordinal) }).Count
            if ($bulletCount -lt 5) { Add-ValidationError "${moduleId}: include at least five actionable instructions" }
        } elseif ($text.StartsWith("---`n", [StringComparison]::Ordinal)) {
            Add-ValidationError "${moduleId}: repository module must not have path frontmatter"
        }

        $detect = Get-ObjectProperty $module "detect"
        if ($null -ne $detect) {
            $detectFiles = @(Get-ObjectProperty $detect "files")
            $contentRules = @(Get-ObjectProperty $detect "content")
            if ($detectFiles.Count -eq 0 -and $contentRules.Count -eq 0) { Add-ValidationError "${moduleId}: detect must contain files or content rules" }
            foreach ($rule in $contentRules) {
                if (@(Get-ObjectProperty $rule "files").Count -eq 0 -or @(Get-ObjectProperty $rule "needles").Count -eq 0) {
                    Add-ValidationError "${moduleId}: every content detector needs files and needles"
                }
            }
        }
    }

    foreach ($source in @(Get-ChildItem -LiteralPath $CatalogRoot -Recurse -File -Filter "*.md")) {
        if ($source.Name -eq "README.md") { continue }
        $prefix = $CatalogRoot.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
        $relative = $source.FullName.Substring($prefix.Length).TrimStart([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar).Replace("\", "/")
        if (-not $represented.ContainsKey($relative)) { Add-ValidationError "catalog markdown not listed in catalog.json: $relative" }
    }
    if (-not $ids.ContainsKey("core")) { Add-ValidationError "catalog must contain the core module" }

    foreach ($presetProperty in @($catalog.presets.PSObject.Properties)) {
        $seen = @{}
        $visiting = @{}
        $resolved = New-Object 'System.Collections.Generic.List[string]'
        function Resolve-ValidationPreset([string]$Name) {
            $property = $catalog.presets.PSObject.Properties[$Name]
            if ($null -eq $property) { throw "Preset references unknown preset '$Name'" }
            if ($visiting.ContainsKey($Name)) { throw "Preset cycle detected at '$Name'" }
            $visiting[$Name] = $true
            foreach ($itemValue in @($property.Value)) {
                $item = [string]$itemValue
                if ($item -eq "*") {
                    foreach ($module in $modules) {
                        $id = [string]$module.id
                        if (-not $seen.ContainsKey($id)) { $seen[$id] = $true; $resolved.Add($id) }
                    }
                } elseif ($item.StartsWith("@")) {
                    Resolve-ValidationPreset $item.Substring(1)
                } else {
                    if (-not $moduleMap.ContainsKey($item)) { throw "Preset '$Name' references unknown module '$item'" }
                    if (-not $seen.ContainsKey($item)) { $seen[$item] = $true; $resolved.Add($item) }
                }
            }
            $visiting.Remove($Name)
        }
        try {
            Resolve-ValidationPreset $presetProperty.Name
            if (-not (@($resolved) -contains "core")) { Add-ValidationError "preset '$($presetProperty.Name)' must include core" }
        } catch {
            Add-ValidationError $_.Exception.Message
        }
    }

    $expectedReviewFiles = @(
        "agents/secure-code-review.agent.md",
        "prompts/secure-code-review.prompt.md",
        "prompts/review-security-changes.prompt.md",
        "prompts/validate-security-finding.prompt.md",
        "skills/secure-code-review-method/SKILL.md",
        "skills/secure-code-review-method/references/workflow.md",
        "skills/secure-code-review-method/references/evidence-and-validation.md",
        "skills/secure-code-review-method/references/review-coverage.md",
        "skills/secure-code-review-method/references/report-template.md"
    )
    foreach ($relative in $expectedReviewFiles) {
        $path = Join-Path $ReviewRoot $relative
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { Add-ValidationError "review pack missing $relative"; continue }
        $text = [IO.File]::ReadAllText($path)
        if (-not $text.Contains($MarkerPrefix)) { Add-ValidationError "review pack file lacks generated marker: $relative" }
        if ($text.Contains("`r")) { Add-ValidationError "review pack file must use LF line endings: $relative" }
    }

    $agentPath = Join-Path $ReviewRoot "agents/secure-code-review.agent.md"
    if (Test-Path -LiteralPath $agentPath -PathType Leaf) {
        $agent = [IO.File]::ReadAllText($agentPath)
        foreach ($tool in @("search/changes", "search/codebase", "read/problems", "search/usages")) {
            if (-not $agent.Contains("'$tool'")) { Add-ValidationError "review agent is missing read-only tool $tool" }
        }
        $frontmatterEnd = $agent.IndexOf("`n---`n", 4, [StringComparison]::Ordinal)
        $frontmatter = if ($frontmatterEnd -ge 0) { $agent.Substring(0, $frontmatterEnd) } else { $agent }
        if ($frontmatter -match '(terminal|execute|edit/|web/fetch|mcp-servers)') { Add-ValidationError "review agent frontmatter contains a non-read-only tool or server" }
        if (-not $agent.Contains("target: vscode")) { Add-ValidationError "review agent must target vscode" }
        if (-not $agent.Contains("disable-model-invocation: true")) { Add-ValidationError "review agent must not be invoked automatically as a subagent" }
    }

    foreach ($prompt in @(Get-ChildItem -LiteralPath (Join-Path $ReviewRoot "prompts") -File -Filter "*.prompt.md")) {
        if (-not ([IO.File]::ReadAllText($prompt.FullName)).Contains("agent: Secure Code Review")) { Add-ValidationError "review prompt must use the Secure Code Review agent: $($prompt.Name)" }
    }
    $skillPath = Join-Path $ReviewRoot "skills/secure-code-review-method/SKILL.md"
    if (Test-Path -LiteralPath $skillPath -PathType Leaf) {
        $skill = [IO.File]::ReadAllText($skillPath)
        if (-not $skill.Contains("name: secure-code-review-method")) { Add-ValidationError "review skill name must match its directory" }
        if (-not $skill.Contains("user-invocable: false")) { Add-ValidationError "review method skill must remain hidden from the slash menu" }
        if (-not $skill.Contains("disable-model-invocation: true")) { Add-ValidationError "review method skill must not load outside an explicit review surface" }
    }

    $pythonSources = @(Get-ChildItem -LiteralPath $PSScriptRoot, (Join-Path $RepoRoot "tests") -Recurse -File -Filter "*.py")
    if ($pythonSources.Count -gt 0) { Add-ValidationError "Python source remains under scripts/ or tests/" }

    if ($Errors.Count -gt 0) {
        foreach ($message in $Errors) { Write-Output "ERROR $message" }
        Write-Error "Validation failed with $($Errors.Count) error(s)."
        exit 1
    }

    $reviewCount = @(Get-ChildItem -LiteralPath $ReviewRoot -Recurse -File).Count
    $presetCount = @($catalog.presets.PSObject.Properties).Count
    Write-Output "Validated $($modules.Count) modules, $presetCount presets, and $reviewCount review-pack files."
    exit 0
} catch {
    Write-Error ("error: " + $_.Exception.Message)
    exit 1
}
